name: my_project_env
channels:
  - pytorch
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.9.13  # or don't specify the version and use the latest stable Python
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  # - poetry=1.*  # or 1.1.*, or no version at all -- as you want
  # - pytorch::pytorch=1.10.0 [build=*cuda112*]
  # # - pytorch::pytorch=1.10.0 
  - pytorch::torchvision=0.11.3 [build=*cuda112*]
  # - pytorch::torchaudio
  - gdal=3.5.0
  - detectron2=0.6.0 [build=*cuda112*]
  - proj
  - geos
  - pypng
  - pygeos
  - geopandas
  - rasterio=1.2.10
  - fiona
  - pycrs
  - descartes
  - opencv 
  - conda-lock
  # - detectron2=0.6.0 

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
